from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Union

class ToolCall(BaseModel):
    id: str
    tool: str
    args: Dict[str, Any]
    result: Optional[str] = None
    status: Optional[str] = None

class Message(BaseModel):
    role: str = Field(..., description="The role of the message author, e.g., 'user', 'assistant', 'system'")
    content: str = Field(..., description="The content of the message")
    toolCalls: Optional[List[ToolCall]] = None

class ChatRequest(BaseModel):
    model: Optional[str] = Field(None, description="The model to use. If not specified, uses the configured default.")
    messages: List[Message] = Field(..., description="The chat history/messages to send to the model.")
    temperature: Optional[float] = Field(0.7, description="Sampling temperature.")

class ChatResponse(BaseModel):
    role: str
    content: str

class AgentRequest(BaseModel):
    query: str = Field(..., description="The prompt or task for the LangGraph agent to handle.")
    model: Optional[str] = Field(None, description="The model to use for the agent nodes.")
    temperature: Optional[float] = Field(0.0, description="Sampling temperature (defaults to 0.0 for deterministic agent routing/replies).")

class AgentResponse(BaseModel):
    category: str = Field(..., description="The classified category of the user query.")
    response: str = Field(..., description="The final answer/response generated by the agent.")
    messages: List[Message] = Field(..., description="The full conversation history of the agent execution.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context or debug info from the agent run.")

class EmbeddingRequest(BaseModel):
    input: Union[str, List[str]] = Field(..., description="The text string or list of text strings to embed.")
    model: Optional[str] = Field(None, description="The model to use for generating embeddings.")

class EmbeddingResponse(BaseModel):
    embeddings: List[List[float]] = Field(..., description="List of generated vector embeddings.")
